version: "3"
services:
  application:
    image: docker-miniproject03-usermanagementapi 
    ports:
      - 8082:8082 
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=ramram
      - MYSQL_DATABASE=jrtp
    volumes:
      - /data/mysql
    # Add network configuration to the mysqldb service
    networks:
      - springboot-db-net
networks:
  springboot-db-net: 