version: "3"
services: 
  application:
    image: springboot-mysql-app
    ports:
      - 8080:8080
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app
  mysqldb:
    image: mysql:8.7
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=ramram
      - MYSQL_DATABASE=jrtp
    volumes:
      - /data/mysql
networks: 
 springboot-db-net: